### ISSUE TITLE
CI: CUDA, conda, windows

### ISSUE THREAD

**Issue by casperdcl** [TomographicImaging/CCPi-Regularisation-Toolkit#195]
- [ ] add CUDA builds
- [ ] add conda release token
- [ ] add windows CPU build & test
- [ ] add windows GPU build
- [ ] deprecate jenkins
